apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pod-dev
  labels:
    app: nginx-pod-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: nginx-pod-dev
    name: us-support-v2-cluster
  source:
    repoURL: https://github.com/nightmar39/cd-five-mins-testing-official.git
    targetRevision: main
    path: ./k8s-resources/nginx-pod/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
