apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-dev
  labels:
    app: express-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: express-dev
    name: CLUSTER_NAME
  project: default
  source:
    path: ./k8s-resources/express/overlays/dev
    repoURL: https://github.com/GITHUB_USER/GITHUB_REPO.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
